# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DoggyPlaydate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoggyPlaydate
  pod 'Firebase/Auth'
  pod 'FirebaseFirestoreSwift', '~> 7.0-beta'
  pod 'Parse'

  target 'DoggyPlaydateTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Parse'
  end

  target 'DoggyPlaydateUITests' do
    # Pods for testing
    pod 'Parse'
  end

end
